/**
 * Dummy data for playground — mirrors Prisma schema exactly.
 * Three documents: Tutorial, Analysis, Mixed
 */

import type { Document } from '@knowledge-engine/types'

const now = new Date('2026-04-14T10:00:00Z')

// ─── TUTORIAL ───────────────────────────────────────────────
export const tutorialDocument: Document = {
  id: 'doc_tutorial_001',
  sourceId: 'src_001',
  transcriptAvailable: true,
  transcriptLanguage: 'en',
  cleanText: `If you ever opened GoHighLevel and felt lost trying to build one of their AI chatbots, you are not alone. There are three different types of AI chatbot builders: guided, prompt-based, and flow-based. Picking the right one saves you hours of rework. In this tutorial we will walk through each type, when to use it, and how to configure your first bot from scratch. Step one: navigate to your sub-account and go to AI Agents, then Conversation AI. Step two: click Create Prompt-Based Bot. Step three: select a template — General Q&A works for most use cases. Step four: name your bot, enable autopilot, and assign channels such as SMS and the chat widget. Step five: set your response time to under 60 seconds and cap messages at 10 per session. Step six: save and proceed to the Knowledge Base to train the bot.`,
  createdAt: now,
  updatedAt: now,
  source: {
    id: 'src_001',
    url: 'https://www.youtube.com/watch?v=demo_tutorial_001',
    sourceType: 'youtube',
    title: 'GoHighLevel AI Chatbot Builders Tutorial (Which One to Use)',
    description: 'Learn which GHL chatbot builder to use and how to set one up in under 5 minutes.',
    duration: 1659, // 27:39
    thumbnail: 'https://img.youtube.com/vi/demo_tutorial_001/maxresdefault.jpg',
    ingestionStatus: 'completed',
    createdAt: now,
    updatedAt: now,
  },
  analysis: {
    id: 'ana_001',
    documentId: 'doc_tutorial_001',
    status: 'completed',
    contentType: 'Tutorial',
    contentTypeReasoning: 'Video walks through step-by-step configuration of GHL Conversation AI with explicit UI navigation paths and expected outcomes.',
    tutorialGoal: 'Set up a functional AI chatbot inside GoHighLevel Conversation AI using the prompt-based builder.',
    summaryShort: 'A walkthrough of the three GHL chatbot builder types — guided, prompt-based, and flow-based — with a full setup demonstration of the prompt-based bot including knowledge base training.',
    summaryDetailed: 'GoHighLevel offers three distinct chatbot builders. The guided form setup is wizard-driven and best for simple FAQ bots with no coding. The prompt-based builder gives you direct control over system instructions and is the most flexible for custom personas. The flow-based builder connects to the visual workflow engine and is appropriate when the bot needs to trigger automations mid-conversation. This tutorial focuses on the prompt-based path: creating a bot, assigning it to channels, configuring autopilot mode, and feeding it a knowledge base.',
    decisionSummary: 'Use prompt-based for custom personas and flexible Q&A. Use guided for speed. Use flow-based only when the bot needs to trigger GHL automations. Do not mix builders on the same primary bot.',
    whatMatters: 'Only the primary bot responds to inbound messages. Assigning the wrong builder type or the wrong channels means your bot silently does nothing — there is no error, just missed conversations.',
    soWhat: 'Before building anything, decide whether your bot needs to trigger workflows. If yes, flow-based. If no, start with prompt-based and a knowledge base. The guided form is a trap for anything beyond basic FAQ.',
    keyPoints: [
      'Only one bot can be set as primary — all inbound messages route there.',
      'Autopilot mode must be enabled or the bot will not respond without human approval.',
      'Knowledge base is where the AI draws its answers — empty KB means generic responses.',
      'Channel assignment (SMS, Facebook, chat widget) must be explicit per bot.',
      'Response time and message limits directly affect cost and conversation quality.',
    ],
    prerequisites: ['Active GHL sub-account', 'At least one phone number or chat widget provisioned', 'Content ready for knowledge base (FAQs, SOPs, or website copy)'],
    howToSteps: [
      {
        step_number: 1,
        title: 'Navigate to Conversation AI',
        instruction: 'From your sub-account dashboard, go to AI Agents in the left sidebar, then select Conversation AI.',
        rationale: 'Conversation AI is only accessible from the sub-account view, not the agency view.',
        ui_path: ['Sub-account', 'AI Agents', 'Conversation AI'],
        tools_or_requirements: ['Sub-account access'],
        expected_outcome: 'You see the Conversation AI Agents screen with a list of bots (empty on first visit).',
        confidence: 'high',
        confidence_reasoning: 'UI path confirmed in transcript with screen recording evidence.',
      },
      {
        step_number: 2,
        title: 'Create a Prompt-Based Bot',
        instruction: 'Click "Create Prompt-Based Bot" in the top right. Select a template — General Q&A is recommended for most use cases.',
        rationale: 'Prompt-based gives you direct control over the system prompt, which is required for custom personas.',
        ui_path: ['Create Prompt-Based Bot', 'Select Template', 'General Q&A'],
        tools_or_requirements: [],
        expected_outcome: 'Bot configuration screen opens with template pre-loaded.',
        confidence: 'high',
        confidence_reasoning: 'Demonstrated directly in tutorial with template selection shown.',
      },
      {
        step_number: 3,
        title: 'Configure Bot Identity and Autopilot',
        instruction: 'Name your bot, toggle Autopilot to ON, and assign the channels it will respond on (SMS, Facebook, Chat Widget).',
        rationale: 'Autopilot is OFF by default. Without it, every response requires manual approval — the bot will not auto-reply.',
        ui_path: ['Bot Name field', 'Autopilot toggle', 'Supported Channels'],
        tools_or_requirements: ['Provisioned phone number for SMS', 'Connected Facebook page for FB channel'],
        expected_outcome: 'Bot shows Active status with assigned channels listed.',
        confidence: 'high',
        confidence_reasoning: 'Clearly demonstrated. Autopilot gotcha explicitly called out in tutorial.',
      },
      {
        step_number: 4,
        title: 'Set Response Time and Message Limits',
        instruction: 'Set response time to under 60 seconds. Set max messages per session to 10 as a starting point.',
        rationale: 'Higher message limits increase AI token costs. Start conservative and increase based on actual conversation data.',
        ui_path: ['Response Time dropdown', 'Max Messages per Session'],
        tools_or_requirements: [],
        expected_outcome: 'Settings saved. Limits visible in bot configuration summary.',
        confidence: 'medium',
        confidence_reasoning: 'Shown in tutorial but optimal values depend on use case — 10 messages may be too low for complex sales conversations.',
      },
      {
        step_number: 5,
        title: 'Train the Knowledge Base',
        instruction: 'Navigate to the Knowledge Base tab. Add content via URL crawl, file upload, or manual text entry. Save and trigger reindex.',
        rationale: 'Without a knowledge base the bot defaults to generic LLM responses which will not reflect your business.',
        ui_path: ['Knowledge Base tab', 'Add Source', 'Save & Reindex'],
        tools_or_requirements: ['Prepared content: FAQs, SOPs, or website URL'],
        expected_outcome: 'Knowledge base shows indexed sources. Bot now draws answers from your content.',
        confidence: 'medium',
        confidence_reasoning: 'Tutorial shows the UI but does not demonstrate reindex confirmation or test query.',
      },
    ],
    implementationNotes: 'GHL sub-account vs agency view is a common source of confusion — Conversation AI is only available in sub-account view. Phone number provisioning can take 24-48 hours; do not test SMS channel immediately after setup. Knowledge base reindexing is asynchronous — wait for confirmation before testing.',
    commonPitfalls: [
      'Setting up the bot in agency view — Conversation AI does not exist there.',
      'Leaving Autopilot OFF and wondering why the bot never responds.',
      'Assigning channels before the phone number is fully provisioned.',
      'Building a knowledge base but not triggering reindex after adding content.',
      'Using the flow-based builder when no workflow triggers are needed — adds unnecessary complexity.',
    ],
    validationChecks: [
      'Send a test SMS to the assigned number — bot should respond within 60 seconds.',
      'Ask the bot a question that is in the knowledge base — answer should reference your content, not generic text.',
      'Check Conversations tab to confirm the bot is logging responses.',
      'Verify bot status shows Active with correct channels listed.',
    ],
    actionItems: [
      'Decide bot type before building: flow-based only if workflow triggers are needed.',
      'Provision phone number at least 48 hours before go-live.',
      'Prepare knowledge base content (minimum: FAQ doc or website URL) before creating the bot.',
      'Test with real SMS after setup, not just the in-app preview.',
    ],
    mechanisms: [],
    keyRisks: [
      'No fallback if knowledge base answer confidence is low — bot may hallucinate.',
      'Token cost scales with message limit × conversations — monitor after launch.',
      'Primary bot restriction means only one bot handles all inbound — plan for handoff scenarios.',
    ],
    claims: [
      'Tutorial claims setup takes 5 minutes — realistic for experienced users, not for first-timers.',
      'Autopilot described as required for auto-responses — confirmed accurate.',
    ],
    critiques: [
      'Tutorial skips knowledge base reindex confirmation — users may test before indexing completes.',
      'No mention of bot handoff to human agent — critical gap for real deployments.',
      'Message limit guidance (10) is arbitrary — no data provided to justify it.',
    ],
    contradictions: [],
    keyItems: [
      { title: 'Guided Form Builder', explanation: 'Wizard-driven setup. Good for simple FAQ bots with no customization needs.', applicability: 'When speed matters more than flexibility.', quality: 'weak' },
      { title: 'Prompt-Based Builder', explanation: 'Direct system prompt control. Best for custom personas and flexible Q&A.', applicability: 'Most agency use cases.', quality: 'strong' },
      { title: 'Flow-Based Builder', explanation: 'Connects bot responses to GHL workflow engine. Required for automation triggers.', applicability: 'When bot needs to trigger pipelines, notifications, or tasks mid-conversation.', quality: 'strong' },
    ],
    keyItemsSynthesis: 'Prompt-based is the right default for 80% of agency use cases. Only reach for flow-based when the conversation needs to trigger downstream automations.',
    domains: ['GoHighLevel', 'AI Chatbots', 'Marketing Automation', 'Agency Operations'],
    keyPoints: [],
    insightScore: 0.62,
    noveltyScore: 0.41,
    confidenceScore: 0.88,
    confidenceReasoning: 'Transcript is clean with explicit UI navigation paths and step confirmations. Insight depth is moderate — tutorial covers setup but not production edge cases. Novelty is low — this is standard GHL configuration content.',
    transcriptQualityScore: 0.91,
    analysisQualityScore: 0.84,
    modelUsed: 'gpt-4o',
    modelProvider: 'openai',
    scoringNotes: ['High transcript quality — captions accurate', 'Tutorial classification confident'],
    assumptions: [],
    contrarians: [],
    commonPitfalls: [
      'Setting up the bot in agency view — Conversation AI does not exist there.',
      'Leaving Autopilot OFF and wondering why the bot never responds.',
      'Assigning channels before the phone number is fully provisioned.',
    ],
    validationChecks: [
      'Send a test SMS — bot responds within 60 seconds.',
      'Ask a KB question — answer references your content, not generic text.',
    ],
    retryCount: 0,
    createdAt: now,
    updatedAt: now,
  },
}

// ─── ANALYSIS / COMMENTARY ──────────────────────────────────
export const analysisDocument: Document = {
  id: 'doc_analysis_001',
  sourceId: 'src_002',
  transcriptAvailable: true,
  transcriptLanguage: 'en',
  cleanText: `AI is not going to replace agencies. But agencies that do not use AI will be replaced by agencies that do. That is the real conversation nobody is having. Every tool vendor is selling you automation. But automation without strategy is just faster failure. The agencies winning right now are not the ones with the most automations — they are the ones who figured out which 20% of their workflow produces 80% of their client results, and automated that 20% relentlessly. The rest? Irrelevant. GoHighLevel is infrastructure. It is not strategy. Confusing the two is the most expensive mistake I see agency owners make.`,
  createdAt: new Date('2026-04-10T10:00:00Z'),
  updatedAt: new Date('2026-04-10T10:00:00Z'),
  source: {
    id: 'src_002',
    url: 'https://www.youtube.com/watch?v=demo_analysis_001',
    sourceType: 'youtube',
    title: 'Why Most Agency AI Automations Fail (And What Actually Works)',
    description: 'A strategic commentary on AI adoption in marketing agencies — what the gurus are not telling you.',
    duration: 1320,
    thumbnail: 'https://img.youtube.com/vi/demo_analysis_001/maxresdefault.jpg',
    ingestionStatus: 'completed',
    createdAt: new Date('2026-04-10T10:00:00Z'),
    updatedAt: new Date('2026-04-10T10:00:00Z'),
  },
  analysis: {
    id: 'ana_002',
    documentId: 'doc_analysis_001',
    status: 'completed',
    contentType: 'Commentary',
    contentTypeReasoning: 'Video presents strong opinions and strategic frameworks without step-by-step instructions. No UI navigation or procedural content.',
    summaryShort: 'A strategic critique of how agencies are adopting AI tools — arguing that most are automating the wrong workflows and confusing tool infrastructure with business strategy.',
    summaryDetailed: 'The creator argues that the AI-vs-agencies narrative is a distraction. The real competitive divide is between agencies that strategically identify high-leverage workflows and automate those specifically, versus agencies that automate broadly and create operational noise. GoHighLevel is positioned as infrastructure, not strategy — a distinction most agency owners miss. The 80/20 principle is applied: find the 20% of workflow that drives 80% of client outcomes, automate that, ignore the rest.',
    decisionSummary: 'Before building any automation, audit your existing workflow to identify which activities directly produce client results. Automate those first. Treat GHL as plumbing, not the product.',
    whatMatters: 'The agencies losing are not losing because they lack tools — they are losing because they are automating low-leverage activities and calling it a strategy. Tool adoption without workflow clarity accelerates mediocrity.',
    soWhat: 'Run a workflow audit before touching another automation. Map every activity to a client outcome. If the connection is not direct, the automation is low priority regardless of how easy it is to build.',
    mechanisms: [
      'Agencies automate broadly because automation is easy and feels like progress, which leads to operational complexity without revenue impact.',
      'Tool vendors incentivize feature adoption, not outcome focus, which leads to agencies measuring automations built rather than client results produced.',
      'High-leverage automations compound — each one reduces friction on the next, which leads to exponential efficiency gains for agencies that start with the right 20%.',
    ],
    keyRisks: [
      'Workflow audit requires honest assessment — most agency owners overestimate the leverage of their current activities.',
      'GHL as infrastructure framing only holds if you have a clear product layer above it — many agencies do not.',
      'The 80/20 claim is directionally useful but not empirically validated for agency operations specifically.',
    ],
    claims: [
      'Automation without strategy is faster failure.',
      'Agencies winning now identified the 20% of workflow driving 80% of results.',
      'GHL is infrastructure, not strategy — confusing the two is the most expensive mistake.',
      'AI will not replace agencies but will replace agencies not using AI.',
    ],
    critiques: [
      'No empirical data provided for the 80/20 claim in agency context.',
      'Workflow audit methodology not defined — advice is directionally correct but not actionable.',
      'No acknowledgment that for early-stage agencies, any automation may be premature.',
    ],
    contradictions: [
      'Claims agencies should automate the 20% of high-leverage work, but earlier argues that most agencies do not know which 20% that is — the advice assumes the answer to the harder problem.',
    ],
    actionItems: [
      'Audit your current workflow: list every recurring activity and map each to a direct client outcome.',
      'Rank activities by revenue or retention impact — automate top 3 before anything else.',
      'Audit your GHL setup for automations that have no clear client outcome connection — pause or delete them.',
    ],
    domains: ['Agency Strategy', 'AI Adoption', 'Business Operations', 'GoHighLevel'],
    keyPoints: [
      'The competitive divide is strategic clarity, not tool access.',
      'Automating the wrong workflows scales mediocrity.',
      'GHL is infrastructure — your strategy lives above it.',
    ],
    insightScore: 0.81,
    noveltyScore: 0.68,
    confidenceScore: 0.79,
    confidenceReasoning: 'Insight depth is high — the infrastructure vs strategy framing is sharp and underrepresented in this niche. Novelty is above average for agency commentary content. Confidence is moderate because claims are opinion-based with no supporting data.',
    transcriptQualityScore: 0.88,
    analysisQualityScore: 0.82,
    modelUsed: 'gpt-4o',
    modelProvider: 'openai',
    scoringNotes: ['Commentary classification confident', 'No step-by-step content found'],
    howToSteps: null,
    prerequisites: null,
    commonPitfalls: [],
    validationChecks: [],
    implementationNotes: null,
    tutorialGoal: null,
    contentTypeReasoning: 'Opinion and strategic commentary — no procedural UI content.',
    keyItems: null,
    keyItemsSynthesis: null,
    assumptions: [],
    contrarians: [],
    retryCount: 0,
    createdAt: new Date('2026-04-10T10:00:00Z'),
    updatedAt: new Date('2026-04-10T10:00:00Z'),
  },
}

// ─── MIXED ───────────────────────────────────────────────────
export const mixedDocument: Document = {
  id: 'doc_mixed_001',
  sourceId: 'src_003',
  transcriptAvailable: true,
  transcriptLanguage: 'en',
  cleanText: `Today we are going to talk about GHL snapshots — what they are, why most people use them wrong, and how to deploy one correctly. A snapshot is a pre-built sub-account configuration. It copies workflows, funnels, pipelines, calendars, and settings into a new sub-account. Here is the problem: most agencies deploy snapshots and then wonder why their clients are confused. The snapshot is not the onboarding. It is the starting line. Step one: go to Agency View, then Accounts, then click the snapshot icon. Step two: select your snapshot from the list. Step three: choose the target sub-account. Step four: confirm the merge strategy — replace existing or merge. Warning: replace will overwrite the client's existing setup. Step five: click deploy and wait for confirmation. Now here is the strategic part most tutorials skip. After deployment, audit the snapshot for dead links, disconnected workflows, and calendar settings that reference your agency's number instead of the client's.`,
  createdAt: new Date('2026-04-12T10:00:00Z'),
  updatedAt: new Date('2026-04-12T10:00:00Z'),
  source: {
    id: 'src_003',
    url: 'https://www.youtube.com/watch?v=demo_mixed_001',
    sourceType: 'youtube',
    title: 'GHL Snapshots: How to Deploy Correctly (And Why Most Agencies Get It Wrong)',
    description: 'Part tutorial, part strategy — how to deploy GHL snapshots without breaking your client accounts.',
    duration: 1980,
    thumbnail: 'https://img.youtube.com/vi/demo_mixed_001/maxresdefault.jpg',
    ingestionStatus: 'completed',
    createdAt: new Date('2026-04-12T10:00:00Z'),
    updatedAt: new Date('2026-04-12T10:00:00Z'),
  },
  analysis: {
    id: 'ana_003',
    documentId: 'doc_mixed_001',
    status: 'completed',
    contentType: 'Mixed',
    contentTypeReasoning: 'Contains both procedural step-by-step snapshot deployment and strategic commentary on post-deployment audit practices.',
    summaryShort: 'A combined tutorial and strategic guide on deploying GHL snapshots correctly — covering UI navigation, merge strategy decisions, and the post-deployment audit most agencies skip.',
    summaryDetailed: 'GHL snapshots allow agencies to replicate sub-account configurations at scale. The tutorial covers deployment mechanics: accessing snapshots from agency view, selecting target accounts, and choosing between replace and merge strategies. The strategic layer addresses the most common post-deployment failures: dead links, disconnected workflows, and calendar settings referencing the wrong phone numbers.',
    decisionSummary: 'Always use merge strategy unless you are setting up a brand new sub-account. Always run a post-deployment audit before handing off to the client. The snapshot is the starting line, not the finish line.',
    whatMatters: 'The replace vs merge decision is irreversible without a backup. Most agencies default to replace without understanding it overwrites existing client configuration — this has caused significant client data loss.',
    soWhat: 'Build a post-deployment audit checklist and make it non-negotiable in your onboarding process. Snapshots without audits are technical debt delivered to clients.',
    mechanisms: [
      'Snapshots copy configuration at the time of creation, which means any updates to the master snapshot do not propagate to deployed sub-accounts automatically.',
      'Replace strategy overwrites existing settings, which leads to data loss if the sub-account already has client-specific configuration.',
    ],
    keyRisks: [
      'Replace strategy is destructive — no undo without a manual backup.',
      'Snapshot content may reference agency-level assets (phone numbers, email addresses) that break in client sub-accounts.',
      'No version control on snapshots — deploying an outdated snapshot silently installs outdated workflows.',
    ],
    claims: [
      'Most agencies deploy snapshots without a post-deployment audit.',
      'Calendar settings commonly reference agency phone numbers after snapshot deployment.',
      'Replace strategy will overwrite existing client configuration.',
    ],
    critiques: [
      'Merge strategy behavior is not fully explained — users need to know what happens on field conflicts.',
      'No mention of snapshot versioning or how to keep master snapshots updated.',
    ],
    contradictions: [],
    howToSteps: [
      {
        step_number: 1,
        title: 'Access Snapshot Deployment',
        instruction: 'Go to Agency View, then Accounts. Find the target sub-account and click the snapshot icon.',
        rationale: 'Snapshot deployment is an agency-level action — not available from sub-account view.',
        ui_path: ['Agency View', 'Accounts', 'Snapshot icon on target account'],
        tools_or_requirements: ['Agency admin access'],
        expected_outcome: 'Snapshot selection modal opens.',
        confidence: 'high',
        confidence_reasoning: 'UI path confirmed with screen recording.',
      },
      {
        step_number: 2,
        title: 'Select Snapshot and Merge Strategy',
        instruction: 'Select your snapshot from the dropdown. Choose merge strategy: use Merge for existing accounts, Replace only for brand new empty sub-accounts.',
        rationale: 'Replace is destructive — it overwrites all existing configuration in the sub-account.',
        ui_path: ['Snapshot dropdown', 'Merge strategy selector'],
        tools_or_requirements: [],
        expected_outcome: 'Snapshot and strategy confirmed in modal.',
        confidence: 'high',
        confidence_reasoning: 'Replace vs merge distinction explicitly demonstrated and warned about.',
      },
      {
        step_number: 3,
        title: 'Deploy and Confirm',
        instruction: 'Click Deploy and wait for the confirmation message. Do not navigate away until confirmation appears.',
        rationale: 'Deployment is asynchronous — navigating away before confirmation may result in partial deployment.',
        ui_path: ['Deploy button', 'Confirmation banner'],
        tools_or_requirements: [],
        expected_outcome: 'Success confirmation shown. Sub-account now has snapshot configuration.',
        confidence: 'medium',
        confidence_reasoning: 'Partial deployment risk mentioned but not demonstrated.',
      },
      {
        step_number: 4,
        title: 'Run Post-Deployment Audit',
        instruction: 'Enter the sub-account and check: all workflow triggers are active, calendar phone numbers reference the client number, funnels have no broken links, and pipeline stages match the client use case.',
        rationale: 'Snapshots bake in agency-level settings that break in client context.',
        ui_path: ['Sub-account', 'Automation', 'Calendars', 'Sites/Funnels'],
        tools_or_requirements: ['Audit checklist'],
        expected_outcome: 'All settings verified and corrected before client handoff.',
        confidence: 'high',
        confidence_reasoning: 'Audit requirement is the core strategic claim of the video — well supported.',
      },
    ],
    implementationNotes: 'Always take a manual note of the client sub-account state before deploying a snapshot to an existing account. GHL does not provide a native rollback. Build your audit checklist as a GHL task or checklist template inside the sub-account itself so it is repeatable.',
    commonPitfalls: [
      'Using Replace strategy on a sub-account that already has client data.',
      'Deploying without checking that the snapshot is the latest version.',
      'Skipping post-deployment audit and handing off a broken environment to the client.',
      'Calendar settings referencing agency phone number — client calls go to the wrong number.',
    ],
    validationChecks: [
      'All workflow triggers show Active status after deployment.',
      'Calendar confirmation SMS/email references client phone number, not agency.',
      'Send a test lead through the pipeline — confirm it moves through stages correctly.',
      'Click through all funnel pages — confirm no broken links or missing images.',
    ],
    actionItems: [
      'Build a post-deployment audit checklist and add it to your standard onboarding SOP.',
      'Default to Merge strategy — only use Replace for genuinely empty new sub-accounts.',
      'Audit your existing deployed snapshots for calendar phone number issues.',
    ],
    domains: ['GoHighLevel', 'Agency Operations', 'Client Onboarding', 'Snapshots'],
    keyPoints: [
      'Snapshot is the starting line, not the finish line.',
      'Replace strategy is destructive — use Merge for existing accounts.',
      'Post-deployment audit is non-negotiable before client handoff.',
    ],
    insightScore: 0.74,
    noveltyScore: 0.55,
    confidenceScore: 0.85,
    confidenceReasoning: 'High confidence — both procedural and strategic content is well-supported by transcript. Insight score reflects the useful but not rare post-deployment audit framing. Novelty is moderate.',
    transcriptQualityScore: 0.89,
    analysisQualityScore: 0.86,
    modelUsed: 'gpt-4o',
    modelProvider: 'openai',
    scoringNotes: ['Mixed classification — tutorial + commentary', 'Replace vs merge warning confirmed'],
    keyItems: null,
    keyItemsSynthesis: null,
    tutorialGoal: 'Deploy a GHL snapshot to a client sub-account without breaking existing configuration.',
    prerequisites: ['Agency admin access', 'Snapshot already created and saved', 'Target sub-account exists'],
    mechanisms: [
      'Snapshots copy configuration at creation time — updates to master do not propagate automatically.',
      'Replace strategy overwrites existing settings — data loss if sub-account is not empty.',
    ],
    contradictions: [],
    claims: [],
    critiques: [],
    assumptions: [],
    contrarians: [],
    retryCount: 0,
    createdAt: new Date('2026-04-12T10:00:00Z'),
    updatedAt: new Date('2026-04-12T10:00:00Z'),
  },
}

export const allDocuments: Document[] = [
  tutorialDocument,
  analysisDocument,
  mixedDocument,
]

export function getDocumentById(id: string): Document | undefined {
  return allDocuments.find(d => d.id === id)
}
